### ISSUE TITLE
MIDDLEWARE_CLASSES deprecated

### ISSUE THREAD

**Issue by vhelke** [tarkatronic/django-requestlogging#1]
Doesn't work with Django 1.11.
MIDDLEWARE_CLASSES have been deprecated: https://docs.djangoproject.com/en/1.11/ref/settings/#middleware-classes.

**Comment by tarkatronic** [comment]
Thank you for the bug report!

I will get to adding this as soon as I can. I'm glad to see this being used; I only released this as a Python 3 compatible version of the original, seemingly abandoned, `django-requestlogging` package.

**Comment by tarkatronic** [comment]
@vhelke I've potentially fixed this in #2 on the `refresh` test branch. Is it possible you can try it out and see if it works for you? The strange part is, the tests were not failing even before my patch. So I may need to add some more tests if this does not work for you.

**Comment by vhelke** [comment]
Hi,
I got futher with this one but still got some errors. Answered in the PR.
Unfortunately don't have time to look into it at the moment. Cheers.

**Comment by tarkatronic** [comment]
Ah, I have a better understanding of the problem now. The way middleware is instantiated is entirely different, which changes things. Now I can tackle the problem a little better. This may take a little bit of work, especially to get some good tests.

**Comment by thefon** [comment]
Thanks, I'm using this also.

Failing for me with:
 ...
    prefix = self.root + '.'
TypeError: unsupported operand type(s) for +: 'function' and 'str'

**Comment by tarkatronic** [comment]
Okay @vhelke @thefon I think I got it fixed. Sorry for the delay! I'm not currently using this in any projects, so the problem didn't stand out very obviously to me at first.

If either of you is able to, can you test with the `refresh` branch, from my PR #2 and see if it works for you? If so, I'll get this bundled up for a new release!
